server {
    listen 80;
    server_name dev.businesscode.com.br;
    location /.well-known/acme-challenge/ { root /var/www/certbot; }
    location / { return 301 https://$host$request_uri; }
}

server {
    listen 443 ssl;
    http2 on;
    server_name dev.businesscode.com.br;

    ssl_certificate     /etc/letsencrypt/live/dev.businesscode.com.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dev.businesscode.com.br/privkey.pem;

    root  /var/www/dash;
    index index.html;

    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;

    location = /index.html {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    location ~* \.(?:css|js|woff2?|svg|png|jpg|jpeg|gif|ico|webp|mp3)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    # SPA fallback (Vue Router em history mode)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
