[program:businesscode-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/businesscode/backend/artisan queue:work database --queue=default --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasof=QUIT
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/businesscode/backend/storage/logs/worker.log
stopwaitsecs=3600

[program:businesscode-campaigns]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/businesscode/backend/artisan queue:work campaigns --queue=campaigns --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasof=QUIT
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/businesscode/backend/storage/logs/worker-campaigns.log
stopwaitsecs=3600

[program:businesscode-scheduler]
process_name=%(program_name)s
command=/bin/bash -c "while true; do php /var/www/businesscode/backend/artisan schedule:run --no-interaction >> /dev/null 2>&1; sleep 60; done"
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/businesscode/backend/storage/logs/scheduler.log
